name: base_sample
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.14.0+3
  flutter_hooks: ^0.16.0
  cupertino_icons: ^1.0.3
  disposable_provider: ^2.3.0

  # http通信
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 自動生成ツール
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1

  # テスト
  mockito: ^5.0.7
  # image_test_utils:
flutter:
  uses-material-design: true
